version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.9.0

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install_dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test --coverage
      - store_artifacts:
          path: coverage
      - run: |
          TAG=$CIRCLE_SHA1
          # docker login -u $DOCKER_USER -p $DOCKER_PASS docker.mad.itera.no
          docker build -t docker.mad.itera.no/itera/ekstern_utlegg:$TAG .
          # docker push docker.mad.itera.no/itera/ekstern_utlegg:$TAG
          docker build -t docker.mad.itera.no/itera/ekstern_utlegg:latest .
          # docker push docker.mad.itera.no/itera/ekstern_utlegg:latest
