version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/node:12.12

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install_dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test --coverage
      - codecov/upload:
          file: coverage/coverage-final.json
      - store_artifacts:
          path: coverage
      - run:
          name: build
          command: yarn build
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker login -u $DOCKER_USER -p $DOCKER_PASS docker.mad.itera.no
          docker build -t docker.mad.itera.no/itera/ekstern_utlegg:$TAG .
          docker push docker.mad.itera.no/itera/ekstern_utlegg:$TAG
          docker build -t docker.mad.itera.no/itera/ekstern_utlegg:latest .
          docker push docker.mad.itera.no/itera/ekstern_utlegg:latest
