version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.9.0

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install_dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test --coverage
      - store_artifacts:
          path: coverage
