{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ekstern-utlegg.serviceAccountName" . }}
  labels:
{{ include "ekstern-utlegg.labels" . | nindent 4 }}
{{- end -}}
