name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - uses: azure/docker-login@v1
        with:
          login-server: itetechmadacr.azurecr.io
          username: ${{ secrets.MAD_DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.MAD_DOCKER_PUSH_PASSWORD }}

      - name: Build image
        run: docker build -t itetechmadacr.azurecr.io/ekstern_utlegg:${{ github.sha }}  -t itetechmadacr.azurecr.io/ekstern_utlegg:latest .

      - name: Push image tag
        run: docker push itetechmadacr.azurecr.io/ekstern_utlegg:${{ github.sha }}

      - name: Push image latest
        run: docker push itetechmadacr.azurecr.io/ekstern_utlegg:latest
